### ISSUE TITLE
【bug】转换后常量和import混在一起了

### ISSUE THREAD

**Issue by yyd1142** [Ziazan/plugin-react-to-vue#1]
**问题一：**
常量GROUP_INFO_ITEM和STATISTICS_DATA_ITEM插入到了import里面了，应该在import 下面
![image](https://user-images.githubusercontent.com/7506695/173292442-1f3802dc-49bd-46f0-8de4-0330a858e87f.png)

**问题二：**
函数方法被直接转换成组件标签了
![image](https://user-images.githubusercontent.com/7506695/173296407-fee2e59a-c87b-4f24-adeb-299439636f13.png)
![image](https://user-images.githubusercontent.com/7506695/173296484-af41857e-bd98-433f-97c7-b72e39b53f42.png)

**文件路径：**
src\page\groupAnalyzV2\groupInfo\index.tsx

**Comment by Ziazan** [comment]
[done](https://github.com/Ziazan/plugin-react-to-vue/commit/e08486e0d1215e17c339a888fed648ef8bfea008)
