### ISSUE TITLE
【bug】转化失败

### ISSUE THREAD

**Issue by yyd1142** [Ziazan/plugin-react-to-vue#2]
**问题一：**
转化之后template为空
![image](https://user-images.githubusercontent.com/7506695/173300188-c0c48b89-cf0d-4ab0-8e90-12e6f79970d1.png)

**文件路径：**
src\page\groupAnalyzV2\groupInfo\components\GroupDescribe\GroupDescribe.tsx

**Comment by Ziazan** [comment]
support exportNamedDeclaration
